version: 0.1
http:
  headers:
    Access-Control-Allow-Origin: ['http://localhost:8080']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS']
    Access-Control-Allow-Headers: ['Authorization']
